---
# code: language=ansible
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
  register: _pre_update_apt_cache
  until: _pre_update_apt_cache is succeeded
  when:
    - ansible_pkg_mgr == "apt"

- name: Ensure dirmngr is installed (gnupg dependency).
  ansible.builtin.apt:
    name: dirmngr
    state: present

- name: Add PPA for Nginx (if configured).
  ansible.builtin.apt_repository:
    repo: 'ppa:nginx/{{ nginx_ppa_version }}'
    state: present
    update_cache: true
  register: nginx_ppa_added
  when: nginx_ppa_use | bool

- name: Ensure nginx will reinstall if the PPA was just added.
  ansible.builtin.apt:
    name: "{{ nginx_package_name }}"
    state: absent
  when: nginx_ppa_added is changed
  tags: ['skip_ansible_lint']
